apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dals
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dals
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-dals
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dals
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dals
    spec:
      containers:
      - image: quay.io/qijing/rhtap-demo-synf-tenant/rhtap-demo-app/hacbs-test-project-dals@sha256:5dee653197bbe1437803996049938fb45ff19b701334d26a4f783b65923fd48a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
